# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true
    # start
    session:
        cookie_secure: auto

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host' ]
    # end

    router:
        default_uri: 'https://thread-talk-f6a6b35bf026.herokuapp.com'

    
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.native
        form:
        csrf_protection:
            enabled: true
            field_name: '_csrf_token'